- name: Install required packages
  become: yes
  package:
    update_cache: yes
    name:
      - nfs-common
    state: latest

- name: Create Velociraptor configs directory
  become: yes
  file:
    path: /etc/velociraptor
    state: directory
    mode: "0770"
    owner: root
    group: velociraptor

- name: Mount EFS to create Velociraptor data directory
  become: yes
  ansible.posix.mount:
    path: /opt/velociraptor
    src: "{{ efs_dns_name }}:/"
    fstype: nfs4
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
    state: mounted

- name: Give Velociraptor user permissions on mounted data directory
  become: yes
  file:
    recurse: yes
    path: /opt/velociraptor
    state: directory
    mode: "0770"
    owner: root
    group: velociraptor